language: java
jdk:
  - oraclejdk9
addons:
  sonarcloud:
    organization: "refactoring-bot"
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
before_install:
  - chmod +x mvnw
script:
  - ./mvnw test -B
  - mvn clean package sonar:sonar
