language: java
jdk:
  - oraclejdk9
addons:
  sonarcloud:
    organization: "refactoring-bot"
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
before_install:
  - chmod +x mvnw
script:
  - git fetch --unshallow --quiet
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Dmaven.test.failure.ignore=false
  # sonar not on pull requests for the moment
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi'
